
scss_files: 'static/css/**/*.scss'

exclude: 'static/css/plugins/**'

linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: true
    character: tab
    allow_non_nested_indentation: true
